---
# tasks file for app-deployment

- name: "Create target source directory"
  file:
    path: "{{ app_deploy_dest }}"
    state: directory

- name: "Create target current directory"
  file:
    path: "{{ symlink_path }}/current"
    state: directory

- name: "Create target old directory"
  file:
    path: "{{ symlink_path }}/old"
    state: directory

- name: "Unarchive app into target source directory"
  unarchive:
    src: "{{ app_src }}"
    dest: "{{ app_deploy_dest }}"
    extra_opts: [--strip-components=1]

- name: "Create settings.cfg file containing all environment variables"
  template:
    src: settings.j2
    dest: "{{ symlink_path }}/current/settings.cfg"

- name: "Create gunicorn.py file containing server configuration"
  template:
    src: gunicorn.j2
    dest: "{{ app_deploy_dest }}/config/gunicorn.py"

- name: "Create a virtualenv"
  shell: "virtualenv {{ env_deploy_dest }}"

- name: "Install pip requirements"
  pip:
    requirements: "{{ app_deploy_dest }}/requirements.txt"
    virtualenv: "{{ env_deploy_dest }}"

- name: "Create old app symlink for the previous version in case of rollback"
  file:
    src: "{{ previous_app_path.stat.lnk_source }}"
    dest: "{{ symlink_path }}/old/app"
    state: link
  when: (previous_app_path.stat.lnk_source is defined)

- name: "Change current app symlink from previous to new version"
  file:
    src: "{{ app_deploy_dest }}"
    dest: "{{ symlink_path }}/current/app"
    state: link

- name: "Create previous env symlink for the previous version in case of rollback"
  file:
    src: "{{ previous_env_path.stat.lnk_source }}"
    dest: "{{ symlink_path }}/old/env"
    state: link
  when: (previous_env_path.stat.lnk_source is defined)

- name: "Change current env symlink from previous to new version"
  file:
    src: "{{ env_deploy_dest }}"
    dest: "{{ symlink_path }}/current/env"
    state: link
